definitions:
  corp.LoginReq:
    properties:
      mobile:
        type: string
      password:
        type: string
    required:
    - mobile
    - password
    type: object
  corp.UserLoginResp:
    properties:
      mobile:
        type: integer
      name:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/core/login:
    post:
      consumes:
      - application/json
      description: corp登录
      parameters:
      - description: login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/corp.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/corp.UserLoginResp'
      summary: corp登录
      tags:
      - corp
swagger: "2.0"
